/*
package com.appiancorp.example;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DefaultSuiteTest {

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver","C:\\Testing_home\\lib\\drivers\\chromedriver.exe");
        driver = new ChromeDriver();
        String baseUrl = "https://www.google.com";
        driver.get(baseUrl);

        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    public String waitForWindow(int timeout) {
        try {
            Thread.sleep(timeout);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        Set<String> whNow = driver.getWindowHandles();
        Set<String> whThen = (Set<String>) vars.get("window_handles");
        if (whNow.size() > whThen.size()) {
            whNow.removeAll(whThen);
        }
        return whNow.iterator().next();
    }
    @Test
    public void clickon14() {
        driver.get("https://keypartnerdemo.appiancloud.com/suite/sites/site-ta");
        driver.manage().window().setSize(new Dimension(1330, 816));
        vars.put("window_handles", driver.getWindowHandles());
        driver.findElement(By.linkText("Link per il workshop del 14 Ottobre")).click();
        vars.put("win7083", waitForWindow(2000));
        vars.put("root", driver.getWindowHandle());
        driver.switchTo().window(vars.get("win7083").toString());
        driver.close();
        driver.switchTo().window(vars.get("root").toString());
        driver.close();
        driver.switchTo().window(vars.get("undefined").toString());
    }
    @Test
    public void click() {
        driver.get("https://keypartnerdemo.appiancloud.com/suite/sites/site-ta");
        driver.manage().window().setSize(new Dimension(1552, 832));
        vars.put("window_handles", driver.getWindowHandles());
        driver.findElement(By.linkText("Link per il workshop del 28 Ottobre")).click();
        vars.put("win3284", waitForWindow(2000));
        vars.put("root", driver.getWindowHandle());
        driver.switchTo().window(vars.get("win3284").toString());
        driver.close();
        driver.switchTo().window(vars.get("root").toString());
    }
    @Test
    public void click28() {
    }
    @Test
    public void relazioni() {
        driver.get("https://keypartnerdemo.appiancloud.com/suite/sites/site-ta");
        driver.manage().window().setSize(new Dimension(1330, 816));
        {
            WebElement element = driver.findElement(By.linkText("Scarica il documento"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.cssSelector(".appian-context-ux-mouse-focus > .SiteMenuTab---nav_label")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".Button---btn"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.cssSelector(".Button---btn")).click();
        js.executeScript("window.scrollTo(0,0)");
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.id("7a537a7f7961711c28f1b5c2f7874ecc")).sendKeys("10/22/1995");
        driver.findElement(By.id("0279ddf2c3ee59c9d2d841f5a998f741")).click();
        driver.findElement(By.id("0279ddf2c3ee59c9d2d841f5a998f741")).sendKeys("3232323");
        driver.findElement(By.id("632f32cde95f4b8c5582571c92db4ab8")).click();
        driver.findElement(By.id("632f32cde95f4b8c5582571c92db4ab8")).sendKeys("isernia");
        driver.findElement(By.id("7d5fc3639986a144919db029936e89da")).click();
        driver.findElement(By.id("7d5fc3639986a144919db029936e89da")).sendKeys("consultant");
        {
            WebElement element = driver.findElement(By.cssSelector(".Button---primary"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.cssSelector(".Button---primary")).click();
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.cssSelector(".appian-context-ux-mouse-focus")).click();
    }
    @Test
    public void relazionifail() {
        driver.get("https://keypartnerdemo.appiancloud.com/suite/sites/site-ta");
        driver.manage().window().setSize(new Dimension(1330, 816));
        driver.findElement(By.cssSelector(".appian-context-ux-mouse-focus > .SiteMenuTab---nav_label")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".Button---btn"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.cssSelector(".Button---btn")).click();
        js.executeScript("window.scrollTo(0,0)");
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.id("6f2b141c7d82f82a4b6402ba5cd1e844")).sendKeys("22/10/1995");
        driver.findElement(By.id("a6127df747cef4f8fb6429cc9bda6330")).click();
        driver.findElement(By.id("a6127df747cef4f8fb6429cc9bda6330")).sendKeys("32323232");
        driver.findElement(By.id("68650706235c267424991695cf358870")).click();
        driver.findElement(By.id("68650706235c267424991695cf358870")).sendKeys("isernia");
        driver.findElement(By.id("9c831073ae9ffbd8fc58106e0b0fb925")).click();
        driver.findElement(By.id("9c831073ae9ffbd8fc58106e0b0fb925")).sendKeys("consultant");
        {
            WebElement element = driver.findElement(By.cssSelector(".Button---primary"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.cssSelector(".Button---primary")).click();
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.cssSelector(".appian-context-ux-mouse-focus")).click();
        driver.close();
    }
    @Test
    public void scaricadocumento() {
        driver.get("https://keypartnerdemo.appiancloud.com/suite/sites/site-ta");
        driver.manage().window().setSize(new Dimension(1330, 816));
        vars.put("window_handles", driver.getWindowHandles());
        driver.findElement(By.linkText("Scarica il documento")).click();
        vars.put("win3252", waitForWindow(2000));
        vars.put("root", driver.getWindowHandle());
        driver.switchTo().window(vars.get("win3252").toString());
        driver.close();
        driver.switchTo().window(vars.get("root").toString());
        driver.close();
    }
    @Test
    public void testinserimento() {
        driver.get("https://keypartnerdemo.appiancloud.com/suite/sites/site-ta");
        driver.manage().window().setSize(new Dimension(1330, 816));
        vars.put("window_handles", driver.getWindowHandles());
        driver.findElement(By.linkText("Link per il workshop del 28 Ottobre")).click();
        vars.put("win5715", waitForWindow(2000));
        vars.put("root", driver.getWindowHandle());
        driver.switchTo().window(vars.get("win5715").toString());
        driver.findElement(By.id("ui-input-1")).sendKeys("Pier");
        driver.findElement(By.id("ui-input-2")).click();
        driver.findElement(By.id("ui-input-2")).sendKeys("Di Pilla");
        driver.findElement(By.cssSelector(".fh:nth-child(1)")).click();
        driver.close();
        driver.switchTo().window(vars.get("root").toString());
        driver.close();
        driver.switchTo().window(vars.get("undefined").toString());
    }
}
*/